insert into oms_products (name, description) values ('Most Beautiful, The (Ichiban utsukushiku)', 'Drama');
insert into oms_products (name, description) values ('Tale of Tales (Skazka skazok)', 'Animation');
insert into oms_products (name, description) values ('Martha Marcy May Marlene', 'Drama|Thriller');
insert into oms_products (name, description) values ('Mortdecai', 'Adventure|Comedy');
insert into oms_products (name, description) values ('Conan O''Brien Can''t Stop', 'Documentary');
insert into oms_products (name, description) values ('Guest of Cindy Sherman', 'Documentary');
insert into oms_products (name, description) values ('Return to Paradise', 'Crime|Drama|Romance|Thriller');
insert into oms_products (name, description) values ('Momma''s Man', 'Drama');
insert into oms_products (name, description) values ('Shot in the Dark, A', 'Comedy|Crime|Mystery');
insert into oms_products (name, description) values ('Birds, The', 'Horror|Thriller');
insert into oms_products (name, description) values ('Bo Burnham: what.', 'Comedy');
insert into oms_products (name, description) values ('Armored', 'Action|Drama|Thriller');
insert into oms_products (name, description) values ('Pitch Black', 'Horror|Sci-Fi|Thriller');
insert into oms_products (name, description) values ('A Connecticut Yankee in King Arthur''s Court', 'Adventure|Children|Comedy|Fantasy');
insert into oms_products (name, description) values ('Switch, The', 'Comedy|Romance');
insert into oms_products (name, description) values ('Phat Girlz', 'Comedy');
insert into oms_products (name, description) values ('Last King of Scotland, The', 'Drama|Thriller');
insert into oms_products (name, description) values ('Homer & Eddie', 'Drama');
insert into oms_products (name, description) values ('From Justin to Kelly', 'Musical|Romance');
insert into oms_products (name, description) values ('Bad Teacher', 'Comedy');